# Generated by Django 5.2.9 on 2025-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('user', 'User')], max_length=50)),
                ('phone', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
